apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-deployment
  labels:
    app: web
#Deployment specifications
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
#Pod specifications
    spec:
      imagePullSecrets:
      - name: dockerhub-secret
      containers:
      -  name: web
         image: mike004/ecom-web:v1
         ports:
         -  containerPort: 80
         livenessProbe:
           tcpSocket:
             port: 80
           initialDelaySeconds: 10
           periodSeconds: 5
           failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 10
            periodSeconds: 5
            failureThreshold:
         #envFrom:
         #- secretRef:
         #  name: db-secret
         env:
         - name: DB_PASSWORD
           valueFrom:
             secretKeyRef:
               name: db-secret #secret name
               key: DB_PASSWORD
         envFrom:
         - configMapRef:
             name: env-configmap

---
apiVersion: v1
kind: Service
metadata:
  name: web-service
spec:
  selector:
    app: web
  type: NodePort
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 80 #need to match container port
      nodePort: 31000 #external port used to access the service
