apiVersion: v1
kind: Service
metadata:
  name: {{.Values.serviceName}}
spec:
  selector:
    {{.Values.serviceSelector}}
  type: {{.Values.serviceType}} #Nodeport/LoadBalancer
  ports:
    - protocol: TCP
      port: {{.Values.servicePort}}
      targetPort: {{.Values.containerPort}}
      nodePort: {{.Values.nodePort}}
