deploymentName: web-deployment
label: "app: web"
replica: 1
matchLabel: "app: web"
imageSecretsName: dockerhub-secret
containerName: web
containerImage:
containerPort: 80
tcpProbePort: 80
httpProbePath: /
httpProbePort: 80
secretName: db-secret
secretKey: DB_PASSWORD
configmapName: env-configmap

serviceName: web-service
serviceSselector: "app: web"
serviceType: NodePort
servicePort: 8080
containerPort: 80
nodePort: 31000
